name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Type check and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Mise
        uses: jdx/mise-action@v2

      - name: Check
        run: mise run check

      - name: Build
        run: mise run build
